name: Lint and Test
on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: bun ci

      - name: Run Lint
        run: bun run lint

      - name: Run Test
        run: bun run test
