name: Lint and Test
on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install Dependencies
        run: bun ci

      - name: Run Lint
        run: bun run lint

      - name: Run Test
        run: bun run test
